spring:
  profiles:
    default: dev
  data:
    mongodb:
      uri: mongodb://test:test@localhost/swiss?authSource=swiss
server:
  port: 4005
springdoc:
  swagger-ui:
    path: /docs
  api-docs:
    path: /docs
custom:
  profileInfo: "Running with DEV profile - Using DEV Database (swiss-db)"
logging:
  level:
    com.swisscom.crud: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG